services:
  - type: web
    name: Manager 
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_IDS
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        sync: false
